<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'php\\codeformatter\\command' => '/Command.php',
            'php\\codeformatter\\formatter' => '/Formatter.php',
            'php\\codeformatter\\sourcecodeline' => '/SourceCodeLine.php',
            'php\\codeformatter\\standards\\abstractstandard' => '/Standards/AbstractStandard.php',
            'php\\codeformatter\\standards\\pear' => '/Standards/Pear.php',
            'php\\codeformatter\\standards\\sipgate' => '/Standards/Sipgate.php',
            'php\\codeformatter\\standards\\standardsfactory' => '/Standards/StandardsFactory.php',
            'php\\codeformatter\\token' => '/Token.php',
            'php\\codeformatter\\token\\classtoken' => '/Token/ClassToken.php',
            'php\\codeformatter\\token\\doccommenttoken' => '/Token/DocCommentToken.php',
            'php\\codeformatter\\token\\opentagtoken' => '/Token/OpenTagToken.php',
            'php\\codeformatter\\tokenizer' => '/Tokenizer.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
// @codeCoverageIgnoreEnd
