<?php // this is an autogenerated file - do not edit (created Fri, 02 Sep 2011 17:42:17 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'php\\codeformatter\\formatter' => '/Formatter.php',
            'php\\codeformatter\\standards\\defaultstandard' => '/Standards/DefaultStandard.php',
            'php\\codeformatter\\standards\\standardinterface' => '/Standards/StandardInterface.php',
            'php\\codeformatter\\token' => '/Token.php',
            'php\\codeformatter\\tokenizer' => '/Tokenizer.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
