<?php // this is an autogenerated file - do not edit (created Mon, 12 Sep 2011 17:32:30 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'php\\codeformatter\\command' => '/Command.php',
            'php\\codeformatter\\formatter' => '/Formatter.php',
            'php\\codeformatter\\sourcecodeline' => '/SourceCodeLine.php',
            'php\\codeformatter\\standards\\abstractstandard' => '/Standards/AbstractStandard.php',
            'php\\codeformatter\\standards\\pear' => '/Standards/Pear.php',
            'php\\codeformatter\\standards\\standardsfactory' => '/Standards/StandardsFactory.php',
            'php\\codeformatter\\token' => '/Token.php',
            'php\\codeformatter\\tokenizer' => '/Tokenizer.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
